### ISSUE TITLE
'og:type' cannot be set by config.yml or controller

### ISSUE THREAD

**Issue by cassianotartari** [sonata-project/SonataSeoBundle#35]
I was trying to set a 'og:type' different from 'article' on my pages using this bundle and SonataPageBundle but my 2 tentatives were failed, the first in config.yml

'og:type':            website

The secont in the controller:

->addMeta('property', 'og:type', 'website')

Another bug was when I tried to add 'og:image:width' the cache:clear throw:

Argument 4 passed to Sonata\SeoBundle\Seo\SeoPage::addMeta() must be of the type array, null given, called in .../vendor/sonata-project/seo-bundle/Sonata/SeoBundle/Seo/SeoPage.php on line 130 and defined in .../vendor/sonata-project/seo-bundle/Sonata/SeoBundle/Seo/SeoPage.php on line 93

The 'article' I think that is being set in .../vendor/sonata-project/page-bundle/Sonata/PageBundle/Page/Service/DefaultPageService.php line 91

$this->seoPage->addMeta('property', 'og:type', 'article');

**Comment by rande** [comment]
This should be fixed.

**Comment by apuzanoff** [comment]
It seems the issue is still here.
I have `<meta property="og:type" content="article" />`
even I've added 'og:type':           website
into config/packages/sonata_seo.yaml
